name: "ph7"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ph7_db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
